name: aripra_mobile_shared_feature
description: A Flutter package for reusable features.
version: 0.0.1
homepage: https://github.com/yourname/my_flutter_package

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # assets:
  #   - assets/images/
