name: aripra_mobile_shared_feature
description: A Flutter package for reusable features.
version: 0.0.1
homepage: https://github.com/yourname/my_flutter_package

environment:
  sdk: ^3.5.3
  
dependencies:
  flutter:
    sdk: flutter
